### ISSUE TITLE
a propos

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#10]
bon je m'en sors mieux maintenant, mais je ne connais pas encore bien le labyrinthe de dossier... :-) 
Je n'arrive pas à trouver le lieux de "a propos" où on avait marqué "on vera plus tard"... 

Merci de me l'indiquer.
Bien cordialement, votre collaborateur yogi... :-)

**Comment by naveau** [comment]
C'est dans le fichier de config du site, ici: https://github.com/n-geoffrey/n-geoffrey.github.io/blob/master/_config.yml

C'est la partie "description"
