### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by naveau** [n-geoffrey/n-geoffrey.github.io#13]
Trouver une petite image pour remplacer le "F" à coté du titre du site dans les onglets

**Comment by n-geoffrey** [comment]
Le logo Saocha se serait super. Je l'achète en rentrant, on fera le test voir si cela fonctionne. :-)

**Comment by naveau** [comment]
Tu peux ajouter une version de bonne qualité du logo dans le dossier "images/" ? Je ferai une version petite pour le favicon.

**Comment by naveau** [comment]
Done
