### ISSUE TITLE
Configuration: sous titre

### ISSUE THREAD

**Issue by naveau** [n-geoffrey/n-geoffrey.github.io#14]
Salut @n-geoffrey !

Est-ce que tu peux aller dans la configuration du projet et changer le sous titre.
Au lieu de :  
 "»Feeling Responsive« is a flexible theme for Jekyll built on Foundation framework. Have a look at... http://phlow.github.io/feeling-responsive/"
J'aimerai bien un truc genre :
"Site de Geoffrey : http://n-geoffrey.github.io"

Comme ça j'ai le lien direct dans l'interface ! Je suis feignant !

**Comment by n-geoffrey** [comment]
c'est fait :-)
