### ISSUE TITLE
Page contact

### ISSUE THREAD

**Issue by naveau** [n-geoffrey/n-geoffrey.github.io#16]
A mettre à jour avec ce que tu veux y mettre !

**Comment by n-geoffrey** [comment]
Il parait qu'il ne vaut mieux pas laisser son téléphone et mail sur un site internet, sinon les robot le récupèrent et c'est pas cool...
On peut utiliser un formulaire comme ils proposent, qui serait redirigé vers g.naveau@hotmail.fr ?
et ou ils peuvent laisser leur numéro et du texte, que je les rappelle ? 

a part cela je ne vois pas quoi mettre dans cette rubrique.

**Comment by naveau** [comment]
Oui on peut faire un formulaire comme il le propose. Je vais créer ça et tu me dira ce que tu en pense.

**Comment by naveau** [comment]
Bon, pour l'instant j'ai mis ton mail geoffrey@saocha-massage.fr
Je pense que ça pourrait être bien de mettre ton numéro de portable aussi pour les rendez vous.

Il faudrait surement étendre un peu la page pour expliquer pourquoi les gens peuvent te contacter :

- prendre un rendez-vous pour un massage
- s'incrire pour un cours de yoga (peut-être renvoyer vers l'association)
- discuter de tout et n'importe quoi !
- etc...

**Comment by naveau** [comment]
Pour l'instant ça me paraît bien.
