### ISSUE TITLE
infos utiles

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#18]
trop cool ! 
Merci pour la mise en page ! 
Je sais pas ce qui avait beugué, mais ça faisait vraiment pas terrible.. ;-) 

voila c'est tout pour cette issue.. ;-)

**Comment by naveau** [comment]
C'est la façon dont tu as inscrit les liens, regarde comment j'ai écrit les adresses.
Le pattern c'est:
```markdown
[mon site de ouf](http://mon-site-de-ouf.fr)
```
