### ISSUE TITLE
Mise en forme de la partie yoga

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#19]
Salut mika. 
Un bon internet en Inde, si si ça existe ! (à Bombay en tout cas. :-)  ). 
Du coup j'en profite pour travailler sur le site. 

J'ai renommer une nouvelle page "agama-yoga" qui décrit en plus bref, et j'ai renommé l'ancienne page agama-yoga en agama-yoga-detail. 

Mais le site continue d'afficher l'ancienne page...

**Comment by naveau** [comment]
Je regarde ça ce soir

**Comment by naveau** [comment]
Ok, je vois pourquoi ça ne marche pas mais je ne comprend pas bien ce que tu veux obtenir au final.
Dis moi la page que tu veux afficher pour ces différents cas:

- Dans le menu
  - l'utilisateur clic sur Yoga -> ?
  - l'utilisateur clic sur Yoga/Agama Yoga -> pages/agama-yoga.md ?
- Dans la page "pages/agama-yoga.md"
  - l'utilisateur clic sur "voir la version détaillée ici" -> pages/agama-yoga-detail.md ?

**Comment by n-geoffrey** [comment]
EN fait c'est bon, c'est parce qu'il y avait un beug dans mon écriture de script d'une page, donc les améliorations d'après n'étaient plus prises en compte... J'ai arrangé cela, du coup tout fonctionne. :-) 

J'ai créé une petite page agama, et "yoga" ainsi que "yoga/agama" y vont... J'aimerais que la page "agama détaillé" soit accessible depuis un hyper lien à la fin de la page actuelle "agama". 
et de la même manière pour la biographie.

**Comment by n-geoffrey** [comment]
J'étais peut être pas clair. En gros les pages vont aux bons endroit par rapport à ce que je souhaite maintenant. :-)

**Comment by naveau** [comment]
Ok, donc il ne manque que le lien vers les pages détaillées.
Il faut qu'on remette un peu d'ordre dans tout ça, je ne suis pas sur que séparer les pages comme ça soit très "intuitif" pour le "client". Il faut qu'on voit ça ensemble à tête reposée. Je vais d'abord regarder ce que tu as écris et je te propose quelque chose.

**Comment by naveau** [comment]
Pour la partie yoga, voila ce que je propose :
- on met en place la partie "blog" du site, c'est à dire une page qui contient les articles que tu écrits au jour le jour.
- le blog contient différentes catégories [Yoga, Ecologie, Végétarien, ...] et on associe les articles que tu as déja écrit sur le yoga à la catgéorie "Yoga"
- dans le menu, on ne laisse qu'une entrée pour la partie yoga (On supprime le sous menu) qui pointe vers la page qui liste tout les articles de la catégorie yoga, ça te permet d'écrire de nouvelles pages yoga si tu veux parler d'un nouveau type de Yoga

- Pour les cours, ateliers, et autres, on fait pareil : un petit article quand tu l'organise (en gros le pdf que tu envoi par mail) et on fait une page qui liste les cours et ateliers

Tu en penses quoi ?

**Comment by n-geoffrey** [comment]
ça me parait super !! 
je peux t'aider à organiser le truc ? Ou je te laisse faire et je remplis ensuite les parties ? 
D'ailleurs la pote qui fait le blog 3h48min va publier un article en me sitant, ça peut être un bon moment pour rendre le site plus visible. Je vais lui demander si je peux le publier sur notre site, je pense qu'elle sera d'accord. :-) 
Merci mika.

**Comment by naveau** [comment]
Ok, je vais m'en occuper.
Pour l'article, ce n'est pas important de le mettre sur le site, c'est plus important qu'elle te cite chez elle avec un lien vers ton site pour ammener les visiteurs !

**Comment by naveau** [comment]
Bon, celui là, j'essai de m'en occuper ce soir ! Je ne m'ennui pas tant que ça au boulot !

**Comment by naveau** [comment]
Bon ça commence à ressembler à qq chose chez moi. On peut se voir un soir pour mettre ça en ligne ?
Je ferme ce ticket et j'en ouvre un autre sur la partie blog: #29
