### ISSUE TITLE
Mise en forme de la partie massage

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#20]
J'ai mis dans la page massage des (voir plus). 
Est-ce possible de faire en sorte que le texte d'explication de chaque massage n'apparaisse que si la personne clique sur (voir plus) ? et sinon il n'apparaitrait que la première phrase d'introduction? 

de la même manière pour la biographie, est-ce possible d'insérer un hyper-lien pour que le "voir plus" à la fin de la page biographie nous amène sur la page "about", qui est la biographie détaillée?  et pareil pour agama-yoga? 

Bon je t'envois cela maintenant mais aucune urgence... On revient dans 2 jours en france, on pourra voir cela tranquillement ensemble.  Des bisous !

**Comment by naveau** [comment]
Je pense qu'il faut créer un post par massage avec une ou deux phrases d'accroches et un texte détaillé qui explique le fonctionnement.
Ensuite, on fait une page massage globale qui fait une liste de tout les massages avec uniquement les phrases d'accroches et un lien vers la page détaillée.

Voici ce que ça pourrait donner : https://phlow.github.io/feeling-responsive/blog/ (Imagine que chaque article de la liste soit un massage)

Tu en penses quoi ?

**Comment by n-geoffrey** [comment]
Ce serait parfait comme cela !

**Comment by naveau** [comment]
Ok, je vais faire le ménage et créer les différents post. Il faudra aussi que je fasse la mise en page pour la page principale.
