### ISSUE TITLE
site map

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#21]
Dans service il y a un onglet site map. Du coup dans la recherche google de saocha massage assez vite on trouve le lien vers cette page incompréhensible... vaudrait mieux l'enlever non?

**Comment by naveau** [comment]
Il faut que je regarde, je crois que cette page est importante pour le référencement mais on peut surement faire en sorte qu'elle ne s'affiche pas comme ça pour l'utilisateur. Si je ne me trompe pas, c'est un peu le sommaire du site.

**Comment by naveau** [comment]
Bon, je ne comprend pas vraiment comment ça marche donc je supprime la page pour le moment.
