### ISSUE TITLE
Mise en forme de la partie biographie

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#22]
La c'est le principal problème qui me reste. 
Quand tu avais remanié les pages, il y avait des espaces et tout ce qu'il faut. 
La c'est un seul bloc.... 
Et aussi pouvoir mettre des tableaux dans "tarifs et horaires".

**Comment by naveau** [comment]
De quelles pages tu parles ? C'est plus simple si tu me mets une liste des liens ou la mise en page ne marche pas, comme ça je ne cours pas partout sur le site !

**Comment by naveau** [comment]
J'ai mis en page la partie biographie, tu me diras ce que tu en pense. Le reste viendra plus tard !
