### ISSUE TITLE
buegue hyper lien pour massages

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#23]
j'ai fais sur le même modèle que pour la biographie, pour renvoyer vers les pages des massages, et quand on clique dessus il propose un téléchargement... WTF ??? 

:-) :-) Cet univers soi disant rationnel de l'ordinateur me laisse pantois... :-)

**Comment by n-geoffrey** [comment]
tu peux tester, cliques sur les (voir plus) après les descriptions des massages...

**Comment by n-geoffrey** [comment]
par contre celui fait dans la page index du yoga fonctionne bien (le lien "voir la version détaillée") pour agama yoga.

**Comment by naveau** [comment]
Il faut ajouter l'extension ".md" à tes fichiers, sinon le site ne comprend pas que ce sont des pages à convertir en html et propose juste au visiteur de télécharger la version brute.
Autre point, ne mets pas d'accent dans les noms de fichier, ce sera plus safe.
