### ISSUE TITLE
compteur GGR... ;-) 

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#25]
Salut Mika. 
Est-il simple d'installer un compteur des passages sur le site ? si oui peux tu le faire ? ;-) 
Je suis curieux de savoir, je pense qu'avec les flyers et maintenant l'annonce officielle, les visites commencent à venir, mais j'aimerai pouvoir me rendre compte. 

Merci à toi, des bisous ! 

Djo

**Comment by naveau** [comment]
C'est un peu compliqué pour un site statique mais je vais me renseigner pour voir avec les solutions google analytic ou autre. Je te tiens au jus.

**Comment by naveau** [comment]
J'ai mis en place un compte google analytic sur le site, on verra comment ça marche sur le tas !!
As tu un compte google ? Il me faudrait ton adresse mail google pour que tu puisse accéder aux stats directement (sinon il faut que je t'envoi un petit pdf chaque semaine !! C'est possible aussi ;p)

**Comment by n-geoffrey** [comment]
geoffrey.n62@gmail.com      il me semble que c'est un compte google.. :-) et je lis les messages qui arrivent dessus.

**Comment by naveau** [comment]
Tu as du recevoir un mail qui te donne l'autorisation de consulter les stats.
