### ISSUE TITLE
mise en page index massage 

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#26]
bon je galère un peu,
- le "voir plus" va pas toujours à la ligne, 
- et les 3# apparaissent sur le site internet, alors que dans la pré-vision sur github ils n'apparaissent pas.

cela dépasse mes capacités... :-) Il faudrait vraiment que l'on bosse un peu ensemble sur les pages que je voie, parce que j'en chie toujours sur les mêmes choses (les phrases ne vont pas à la ligne alors qu'elles sont tapées sur des lignes différentes etc). 
Des bisous !

**Comment by naveau** [comment]
Done by 7d57f43570d49769134e210d061040c03f1bec21
