### ISSUE TITLE
les photos ! 

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#27]
1) peux-tu essayer de mettre la photo (vue-mer) en photo principale du haut ? Mais ) à mon avis la qualité n'est pas assez bonne.
2) Mettre la photo "épaules-huiles" comme photo pour la page principale ? (j'ai testé de la modifier, à voir...).
3) Rétrécir un peu les photos, elles sont chouettes mais trop grande je pense..

**Comment by naveau** [comment]
L'image vue-mer n'est pas l'imge original. Tu as un lien vers l'image?

j'ai vu que tu avais fais des tests pour les photos pour la page principale. c'est cool !
L'idée, c'est que les photos fasse exactement la même taille que celle de [Shiva](https://github.com/n-geoffrey/n-geoffrey.github.io/blob/master/images/Shiva.jpg)

**Comment by naveau** [comment]
Done by 7d57f43570d49769134e210d061040c03f1bec21 and 31fb300f5a8bc1d230cd890bcd6c5901ebe25adb
