### ISSUE TITLE
Rectangle promotion ! 

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#28]
Salut Mika. 
Est-il possible de faire un encadré "promotion", bien visible sur la page d'accueil (et peut être aussi sur la page des massages) du genre : 

"Offre spéciale : : Votre premier massage personalisé d'une heure à 30€. 
 Offre valable jusqu'au 31 Avril 2016  "

Des bisous  !

**Comment by naveau** [comment]
Oui c'est possible, on va ajouter ça !

**Comment by naveau** [comment]
Hihi, je vois que tu t'es essayé à mettre ça cet après midi ;p
Bien joué !

**Comment by naveau** [comment]
J'ai un peu modifié la mise en page pour faire plus jolie.
Et au fait, personnalisé ça prend 2 n... J'ai corrigé les liens ;-p
