### ISSUE TITLE
enlever l'onglet "yoga et sexualite"

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#8]
d'après Clem, trop bizarre pour pouvoir le mettre sur le même site que les massages... Je suis assez d'accords... :-)
J'arrive plus à trouver où on avait rentrer ces infos... 
à la place on peut peut être mettre "stage d'initiation aux massages".

**Comment by naveau** [comment]
Tu veux mettre les "stages d'initiation aux massages" le menu Yoga? Je ne comprend pas bien...
Je supprime l'entrée "yoga et sexualité" en attendant.

**Comment by n-geoffrey** [comment]
non effectivement je me suis emmélé les pinceaux... :-).
on pourrait mettre "yoga et occident".
Merci ! 
PS : peux-tu me dire ou on accède aux modif de cette première page ? des bisous !

**Comment by naveau** [comment]
Pour le menu c'est ici: https://github.com/n-geoffrey/n-geoffrey.github.io/blob/master/_data/navigation.yml

Je ferme donc le ticket et je te laisse l'éditer comme tu veux.
