### ISSUE TITLE
Calendrier/Agenda yoga et massage

### ISSUE THREAD

**Issue by n-geoffrey** [n-geoffrey/n-geoffrey.github.io#9]
créer les pages pour yoga et massages et les remplir. 
inclure un tableau excel ??

**Comment by naveau** [comment]
Il faut qu'on en discute de vive voix je pense.
Par exemple, pour les massages, les tarifs ne vont pas trop changer et les horaires dépendent de la demande. Je pense que dans ce cas, on doit inciter les gens à te contacter directement pour avoir un rendez-vous.
Pour le Yoga, il faut indiquer les horaires des cours réguliers mais aussi faire une partie annonce ou il y aura les évènements ponctuels type séminaires, journée découverte, etc...

**Comment by n-geoffrey** [comment]
yep, à voir. 
Pour les massages j'adorerais avoir un calendrier sur le site, où les gens puissent s'inscrire . Je recevrais un mail ou un sms , et si je confirme ils reçoivent un mail et /ou sms de confirmation de rendez-vous... tu crois que c'est possible ça ?? ou dans un 2ème temps, plus tard ??
Et du coup ils pourraient remplir leur nom prénom, mail et téléphone. et en même temps on leur demanderait si ils acceptent de recevoir des mails d'infos pour le yoga et/ou le massage.   :-)

**Comment by naveau** [comment]
Le principe de ce blog est qu'il est simple et gratuit mais on ne peut pas vraiment faire de truc ou les gens modifie le site (comme laisser un message). 
Pour faire ça on doit utiliser d'autres applications. Je vais chercher ce qui peut marcher et on en reparle.

**Comment by naveau** [comment]
Pour les tarifs, voir #20 et #19
Je renomme ce ticket pour la partie calendrier

**Comment by naveau** [comment]
On en est où de tes besoins pour la partie calendrier/prise de rendez-vous ? Est-ce toujours aussi nécessaire/urgent ? Je n'ai pas vraiment eu le temps de regarder... dsl ;p

**Comment by n-geoffrey** [comment]
Il n'est pas du tout urgent (encore très peu de visite sur le site, de personnes déjà intéressées par mes massages, donc elles vont m'appeller pour un RDV). 
On pourrait faire un tableau de plages horaires préférentielles dans la semaine (fixe et théoriques, pour donner une idée aux ges de mes dispo). Si je te le fais par excel tu pourras l'inclure sur le site, ou il faut que j'utilise un autre moyen? 
on vera plus tard si la fonction prise de RDV devient vraiment nécessaire...

**Comment by naveau** [comment]
Donnes-moi juste tes horaires par jour ici, je metterai en forme pour le site.
